version: '3.8'

services:
  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db-data:

